config/routes.rb
Rails.application.routes.draw do

	root 'home#top'
	get 'home/about'
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :book_comments, only: [:create, :destroy]
	  resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  validates :name, length: { minimum: 2, maximum: 20 }, presence: true
  validates :introduction, length: { maximum: 50 }

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
   @user = User.find(params[:id])
   @review = Book.new
   @books = Book.all
 end

 def edit
  @user = User.find(params[:id])
  if @user == current_user
    render "edit"
  else
    redirect_to user_path(current_user.id)
  end
end

def index
 @user = current_user
 @review = Book.new
 @users = User.all
end

def update
 @user = User.find(params[:id])
 if @user.update(user_params)
  redirect_to user_path(@user), flash: {success: "You have updated user successfully."}
else
  render :edit
end
end

def following
  @user = User.find(params[:id])
  @users = @user.followings
  render 'show_follow'
end

def followers
  @user = User.find(params[:id])
  @users = @user.followers
  render 'show_follower'
end

private
def user_params
 params.require(:user).permit(:name, :introduction, :profile_image)
end
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
		user == current_user
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
<div><%= f.hidden_field :following_id %></div>
<%= f.submit "フォローする", class: "bnt btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'users/unfollow' %>
		<% else %>
			<%= render 'users/follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followings.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		follwers
	</a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete}) do |f| %>
<%= f.submit "フォローを外す", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/_user_mene.html.erb
<div class="user_mene">

  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
  <table class="table">
    <tr><th>name</th><td><%= user.name %></td></tr>
    <tr><th>introduction</th><td><%= user.introduction %></td></tr>
  </table>

  <%= link_to edit_user_path(user) do %>
  <span class="glyphicon glyphicon-wrench btn btn-default btn-block" aria-hidden="true"></span>
  <% end %>
</div>

app/views/users/_user_menu.html.erb
<div class="user_menu">

  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
  <table class="table">
    <tr><th>name</th><td><%= user.name %></td></tr>
    <tr><th>introduction</th><td><%= user.introduction %></td></tr>
    <tr><th><%= render 'users/follow_form' %></th></tr>
    <tr><th><%= render 'users/stats' %></th></tr>
  </table>

  <% if current_user.id == user.id %>
    <%= link_to edit_user_path(user) do %>
    <span class="glyphicon glyphicon-wrench btn btn-default btn-block" aria-hidden="true"></span>
    <% end %>
  <% else %>
    <%= link_to user_path(current_user.id) do %>
    <span class="glyphicon glyphicon-wrench btn btn-default btn-block" aria-hidden="true"></span>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>




<% if @user.errors.any? %>
  <div class = "alert">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>




<%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  </div>

  <div class="field">
      <%= f.label :introduction %>
      <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
    </div>

    <div class="actions">
      <%= f.submit "Update User" %>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<%= render 'layouts/notifications' %>
	<div class="row">
		<div class="col-xs-3">
			<%= render partial: 'users/user_menu', locals: { user: @user } %>
			<%= render partial: 'books/new', locals: { review: @review } %>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr><th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %></td>
					<td><%= user.name %> </td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<% unless current_user?(user) %>
					<td id="follow_form">
						<% if current_user.following?(user) %>
							<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete}) do |f| %>
							<%= f.submit "フォローを外す", class: "btn btn-large follow-btn" %>
							<% end %>
						<% else %>
							<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
							<div><%= f.hidden_field :following_id %></div>
							<%= f.submit "フォローする", class: "bnt btn-large btn-primary follow-btn" %>
							<% end %>
						<% end %>
					</td>
					<% end %>
					<td><%= link_to "Show",user_path(user) %>
					</td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<%= render 'layouts/notifications' %>
	<div class="row">
		<div class="col-xs-3">
			<%= render partial: 'users/user_menu', locals: { user: @user } %>
			<%= render partial: 'books/new', locals: { review: @review } %>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover">
				<thead>
					<tr><th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<% @books.each do |book| %>
					<% if book.user.id == @user.id %>
						<tr>
							<td><%= link_to user_path(@user) do %>
								<%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %>
								<% end %>
							</td>
							<td><%= link_to book.title, book_path(book) %> </td>
							<td><%= book.body %> </td>


							<% if book.favorited_by?(current_user) %>
								<td><%= link_to book_favorites_path(book), method: :delete do %>
									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									<%= book.favorites.count %>
									<% end %>
								</td>
								<% else %>
								<td>
									<%= link_to book_favorites_path(book), method: :post do %>
									<i class="fa fa-heart-o" aria-hidden="true"></i>
									<%= book.favorites.count %>
									<% end %>
								</td>
							<% end %>
							<td>コメント数：<%= book.book_comments.count %></td>
						</tr>
					<% end %>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<% if @user.followings.blank? %>
	<p>フォロワーはいません。</p>
	<% else %>
		<h2>Follow Users</h2>
		<table class="table">
			<thead>
				<tr><th>image</th>
					<th>name</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<% @user.followings.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %></td>
				<td><%= user.name %> </td>
				<td>フォロー数：<%= user.followings.count %></td>
				<td>フォロワー数：<%= user.followers.count %></td>
				<td><%= link_to "Show",user_path(user) %></td>
		</tr>
	<% end %>
	</table>
<% end %>

app/views/users/show_follower.html.erb
<% if @user.followers.blank? %>
	<p>フォロワーはいません。</p>
	<% else %>
		<table class="table">
			<thead>
				<tr><th>image</th>
					<th>name</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
		<% @user.followers.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %></td>
				<td><%= user.name %> </td>
				<td>フォロー数：<%= user.followings.count %></td>
				<td>フォロワー数：<%= user.followers.count %></td>
				<td><%= link_to "Show",user_path(user) %></td>
			</tr>
		<% end %>
	</table>
<% end %>