config/routes.rb
Rails.application.routes.draw do

	root 'home#top'
	get 'home/about'
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :book_comments, only: [:create, :destroy]
	  resource :favorites, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	
	validates :title, presence: true
  	validates :body, presence: true,length: { maximum: 200 }

  	def favorited_by?(user)
  		favorites.where(user_id: user.id).exists?
  	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!


	def index
		@user = User.find(current_user.id)
		@review = Book.new
		@books = Book.all
	end

	def show
		@comments = BookComment.all
		@book = Book.find(params[:id])
		@user = @book.user
		@review = Book.new
		@book_comment = BookComment.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user == current_user
			render :edit
		else
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book), flash: {success: "You have updated book successfully."}
		else
			render :edit
		end

	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	def create
		@review = current_user.books.new(book_params)
		if @review.save
			redirect_to book_path(@review), flash: {success: "You have creatad book successfully."}
		else
			@user = User.find(current_user.id)
			@books = Book.all
			render :index
		end
	end



	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_new.html.erb
<div class="new_book">
  <h2>New book</h2>
  <%= form_for review do |f| %>
  <div class="col-3">
    <div class="form-group">
      <label for="usr"><%= f.label :Title %></label>
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="col-3">
    <div class="form-group">
      <label for="usr"><%= f.label :Opinion %></label>
      <%= f.text_area :body %>
    </div>
  </div>
  <%= f.submit "Create Book", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<%= render 'layouts/notifications' %>
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1>Editing Book</h1>
			<%= form_for @book do |f| %>
			<% if @book.errors.any? %>
			<div id="error_explanation">
				<h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
				<ul>
					<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<div class="form-group">
				<label for="usr"><%= f.label :Title %></label>
				<%= f.text_field :title, autofocus: true, class: "form-control" %>
			</div>
			<div class="form-group">
				<label for="usr"><%= f.label :Opinion %></label>
				<%= f.text_area :body, class: "form-control" %>
			</div>
			<%= f.submit "Update Book", class: "btn btn-primary btn-block" %>
			<% end %>
			<div class="m-3">
				<%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
			</div>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<% if @review.errors.any? %>
	<div id="error_explanation">
		<h2><%= @review.errors.count %>errors prohibited this obj from being saved:</h2>
		<ul>
			<% @review.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<%= render 'layouts/notifications' %>
	<div class="row">
		<div class="col-xs-3">
			<%= render partial: 'users/user_menu', locals: { user: @user } %>
			<%= render partial: 'books/new', locals: { review: @review } %>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover">
				<thead>
					<tr><th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<% @books.each do |book| %>
				<tr>
					<td><%= link_to user_path(book.user.id) do %>
						<%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %>
						<% end %>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
						<% if book.favorited_by?(current_user) %>
						<td><%= link_to book_favorites_path(book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							<%= book.favorites.count %>
							<% end %>
						</td>
						<% else %>
						<td>
							<%= link_to book_favorites_path(book), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= book.favorites.count %>
							<% end %>
						</td>
						<% end %>
						<td>
							コメント数：<%= book.book_comments.count %></p>
						</td>
					</td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">

	<%= render 'layouts/notifications' %>
	<div class="row">
		<div class="col-xs-3">
			<%= render partial: 'users/user_menu', locals: { user: @user } %>
			<%= render partial: 'books/new', locals: { review: @review } %>
		</div>
		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<tr>
					<td><%= link_to user_path(@user) do%>
						<%= attachment_image_tag @user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %>
						<br><%= @user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %> </td>
					<td><%= @book.body %></td>
					<% if @book.favorited_by?(current_user) %>
						<td><%= link_to book_favorites_path(@book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							<%= @book.favorites.count %>
							<% end %>
						</td>
					<% else %>
						<td>
							<%= link_to book_favorites_path(@book), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
							<%= @book.favorites.count %>
						<% end %>
						</td>
					<% end %>
						<td>コメント数：<%= @book.book_comments.count %></td>
					<% if @book.user == current_user %>
					<td><%= link_to edit_book_path(@book) do %>
						<button class="btn btn-success">Edit</button>
						<% end %></td>
						<td><%= link_to book_path(@book), method: :delete ,data: { confirm: '本当に消しますか？' } do %>
							<button class="btn btn-danger">Destroy</button>
							<% end %>
						</td>
					<% end %>
					</tr>
				</table>
				<table>
					<% @comments.each do |book_comment| %>
						<% if book_comment.book_id == @book.id %>
							<tr>
								<td><%= attachment_image_tag book_comment.user,:profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: " pull-left" %>
									<br><%= book_comment.user.name %>
								</td>
								<td><%= book_comment.comment %></td>
								<% if book_comment.user == current_user %>
									<td><%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete do %>
										<button class="btn btn-danger">Destroy</button>
									<% end %>
									</td>
								<% end %>
							</tr>
						<% end %>
					<% end %>
				</table>
				<%= form_for [@book, @book_comment] do |f| %>
					<% if @book_comment.errors.any? %>
						<div id="error_explanation">
							<h2><%= @book_comment.errors.count %>errors prohibited this obj from being saved:</h2>
							<ul>
								<% @book_comment.errors.full_messages.each do |message| %>
									<li><%= message %></li>
								<% end %>
							</ul>
						</div>
					<% end %>
					<div class="row">
						<div class="col-sm-12">
							<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
						</div>
					</div>
					<%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
				<% end %>
			</div>
		</div>
	</div>