config/routes.rb
Rails.application.routes.draw do

	root 'home#top'
	get 'home/about'
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :book_comments, only: [:create, :destroy]
	  resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	
	validates :title, presence: true
  	validates :body, presence: true,length: { maximum: 200 }

  	def favorited_by?(user)
  		favorites.where(user_id: user.id).exists?
  	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	validates :comment, presence: true
	belongs_to :book
	belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :following, class_name: "User"
	validates :follower, presence: true
	validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  validates :name, length: { minimum: 2, maximum: 20 }, presence: true
  validates :introduction, length: { maximum: 50 }

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource.id)

	end

	def after_sign_out_path_for(resource)
		root_path
	end




	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name ,:email])
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		book = Book.find(params[:book_id])
		comment = BookComment.new(book_comment_params)
		comment.book_id = book.id
		comment.user_id = current_user.id
		comment.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
		redirect_back(fallback_location: root_path)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!


	def index
		@user = User.find(current_user.id)
		@review = Book.new
		@books = Book.all
	end

	def show
		@comments = BookComment.all
		@book = Book.find(params[:id])
		@user = @book.user
		@review = Book.new
		@book_comment = BookComment.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user == current_user
			render :edit
		else
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book), flash: {success: "You have updated book successfully."}
		else
			render :edit
		end

	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	def create
		@review = current_user.books.new(book_params)
		if @review.save
			redirect_to book_path(@review), flash: {success: "You have creatad book successfully."}
		else
			@user = User.find(current_user.id)
			@books = Book.all
			render :index
		end
	end



	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = Favorite.new(book_id: book.id)
		favorite.user_id = current_user.id
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = Favorite.find_by(book_id: book.id)
		favorite.user_id = current_user.id
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@user = User.find(params[:relationship][:following_id])
		current_user.follow!(@user)
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@user = Relationship.find(params[:id]).following
		current_user.unfollow!(@user)
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
   @user = User.find(params[:id])
   @review = Book.new
   @books = Book.all
 end

 def edit
  @user = User.find(params[:id])
  if @user == current_user
    render "edit"
  else
    redirect_to user_path(current_user.id)
  end
end

def index
 @user = current_user
 @review = Book.new
 @users = User.all
end

def update
 @user = User.find(params[:id])
 if @user.update(user_params)
  redirect_to user_path(@user), flash: {success: "You have updated user successfully."}
else
  render :edit
end
end

def following
  @user = User.find(params[:id])
  @users = @user.followings
  render 'show_follow'
end

def followers
  @user = User.find(params[:id])
  @users = @user.followers
  render 'show_follower'
end

private
def user_params
 params.require(:user).permit(:name, :introduction, :profile_image)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
		user == current_user
	end
end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "flash flash_#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2.0</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/49e942acef.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="nav navbar-inverse">
    <div class="container">
      <div class="nav navbar-left">
        <h3 class="nav navbar text-white p-0 m-0">Bookers</h3>
      </div>
       <nav class="nav navbar navbar-right m-0 p-0">
       <ul class="nav navbar m-0 p-0">
        <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id) do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"><span/> Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path do%>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path do%>
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> logout
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to root_path do %>
            <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path do %>
            <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
            <i class="fas fa-user-check"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
            <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header><!-- /header -->
    <%= yield %>
  <small class="offset-8">©CopyRight Infratop.inc</small>
</body>
</html>